// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
// import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5UxmC6xnJv3DD4a1fhQp4u7odYs3wxKk',
    appId: '1:859969767598:web:b4a5ed24c9fde28ec7853f',
    messagingSenderId: '859969767598',
    projectId: 'fsm-agent',
    authDomain: 'fsm-agent.firebaseapp.com',
    storageBucket: 'fsm-agent.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcXUk3zHreDt5VMXXCoA0UVA_SdTlg4co',
    appId: '1:859969767598:android:716d1a5ae5bc89f1c7853f',
    messagingSenderId: '859969767598',
    projectId: 'fsm-agent',
    storageBucket: 'fsm-agent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt1TtD1rC4mthpwcQFbsU-1ayRUYpWRTI',
    appId: '1:859969767598:ios:a82f59d639a80f2ac7853f',
    messagingSenderId: '859969767598',
    projectId: 'fsm-agent',
    storageBucket: 'fsm-agent.appspot.com',
    iosClientId:
        '859969767598-vhdbnh8umcq8jt7pfnlfpk18slc7nqp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fsmAgent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt1TtD1rC4mthpwcQFbsU-1ayRUYpWRTI',
    appId: '1:859969767598:ios:a82f59d639a80f2ac7853f',
    messagingSenderId: '859969767598',
    projectId: 'fsm-agent',
    storageBucket: 'fsm-agent.appspot.com',
    iosClientId:
        '859969767598-vhdbnh8umcq8jt7pfnlfpk18slc7nqp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fsmAgent',
  );
}
